server:
  port:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/  # Eureka 注册中心的 URL

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&verifyServerCertificate=false&useSSL=false&allowMultiQueries=true
    username: root
    password: '020511'
  application:
    name: product-service